version: "3.8"

services:
  myApp:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_NAME: tree_category
      DB_HOST: postgres_db
      DB_PASSWORD: 2610
      DB_PORT: 5432
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: tree
      POSTGRES_USER: tree
      POSTGRES_DB: tree_category
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: {}